#!/usr/bin/python

import sys
import json

for line in sys.stdin.readlines():
    try:
        j = json.loads(line)
        print(json.dumps(j, separators=(', ',': '), indent=4, sort_keys=True))
    except ValueError, e:
        sys.exit("Not JSON: " + line) # Could print line but JSON is expected.
