#!/usr/bin/python

# To eliminate key order variation in test output. Expects each line to be
# JSON object or array, to match datalackey output.

import sys
import json

for line in sys.stdin.readlines():
    try:
        j = json.loads(line)
        print(json.dumps(j, separators=(',',':'), sort_keys=True))
    except ValueError, e:
        sys.exit("Not JSON: " + line) # Could print line but JSON is expected.
