#!/usr/bin/python

# Exists to make output more readable by humans for the rare occurrences
# when output needs to be understood.

import sys
import json

for line in sys.stdin.readlines():
    try:
        j = json.loads(line)
        print(json.dumps(j, separators=(', ',': '), indent=4, sort_keys=True))
    except ValueError, e:
        sys.exit("Not JSON: " + line) # Could print line but JSON is expected.
